# Generated by Django 4.2.5 on 2023-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPI', '0004_alter_order_parcelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.TextField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='Processing'),
        ),
    ]
