apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'django-api'
        static_configs:
          - targets: ['django-service:8000']
        metrics_path: /metrics/

      - job_name: 'postgresql'
        static_configs:
          - targets: ['postgres-service:5432']


          